### ISSUE TITLE
Optimize_dataset procedure 

### ISSUE THREAD

**Issue by BomboButt** [iRapha/replayed_distillation#1]
Hi, @iRapha 
I got a question: 
For now,
I've followed the steps according to what you mentioned in README file, 
and have finished **training** and **compute-stats** for _hinton1200 model_ on mnist dataset.
It will generate new optimized dataset, and will be stored in **_many_** numpy files in **_/experiments/data/data_optimized_top_layer_experiment_[0:9](clss)_[0:299](batch).npy_**

But, for the next step: **distill**, which requires the optimized dataset got from the previous steps,
according to your command:
```
python main.py --run_name=experiment --model=hinton1200 \
    --dataset=summaries/experiment/data/data_optimized_top_layer_experiment.npy \
    --procedure=distill \
    --model_meta=summaries/experiment/train/checkpoint/hinton1200-8000.meta \
    --model_checkpoint=summaries/experiment/train/checkpoint/hinton1200-8000 \
    --eval_dataset=mnist --student_model=hinton800 --epochs=30 --lr=0.00001
```
We need to input a _data_optimized_top_layer_experiment.npy_ dataset, however, 
we got several and separated npy optimized dataset at the previous step.

Do I need to do any **further command** or surgery on those optimized datasets,
to make it **integrated as one dataset** (i.e. _summaries/experiment/data/data_optimized_top_layer_experiment.npy_ )?

**Comment by irapha** [comment]
Hey, thanks for noticing it. We forgot to update the readme after we made that change.
If you want to use an optimized dataset, please use the path like so:

`summaries/experiment/data/data_optimized_top_layer_experiment_<clas>_<batch>.npy`

I've updated the readme to reflect this. Let me know if this fixes it.

Also note that currently the spectral optimization objectives are not working. I'm waiting on my collaborator to push changes that will fix them. @StefanoFenu

**Comment by BomboButt** [comment]
Dear @iRapha:
Hi, thanks for your quick reply.

However, when I type the command as you suggested:
```
python main.py --run_name=experiment --model=hinton1200 \
    --dataset=summaries/experiment/data/data_optimized_top_layer_experiment_<clas>_<batch>.npy \
    --procedure=distill \
    --model_meta=summaries/experiment/train/checkpoint/hinton1200-8000.meta \
    --model_checkpoint=summaries/experiment/train/checkpoint/hinton1200-8000 \
    --eval_dataset=mnist --student_model=hinton800 --epochs=30 --lr=0.00001
```
The error will become:

> -bash: clas: No such file or directory

(The command and error message are attached as following picture)
![image](https://user-images.githubusercontent.com/17549263/35775175-ed3eceda-09be-11e8-9834-4d23abd7b9c7.png)

And, I also double checked, there's no file named as: `summaries/experiment/data/data_optimized_top_layer_experiment_<clas>_<batch>.npy`
Instead, the optimized dataset in that directory are named as:
![image](https://user-images.githubusercontent.com/17549263/35775199-855c1fce-09bf-11e8-8649-9d18c3a3a55f.png)

Did I mistake something or lose any file?

**Comment by irapha** [comment]
Ops, yes that error is because `<` and `>` are special characters in bash. The correct way to use this should be with quotes around the file name:

`--dataset="summaries/experiment/data/data_optimized_top_layer_experiment_<clas>_<batch>.npy"`

as opposed to:

`--dataset=summaries/experiment/data/data_optimized_top_layer_experiment_<clas>_<batch>.npy`

Don't worry about this file not existing. The distill script will replace `<clas>` with the class name and `<batch>` with a random batch in that class.

Let me know if this works

**Comment by BomboButt** [comment]
Ah ha!!! Yes, this works.
Thank you for your helps!! @iRapha
