### ISSUE TITLE
Wrong command for visualization.

### ISSUE THREAD

**Issue by BomboButt** [iRapha/replayed_distillation#2]
Hi, @iRapha:
Here I come again, hahah... :dancing_men: 
For the second command for visualization per-class and per-pixel means,
the documentation suggests us to have cmd like:
```
python viz/print_stats.py \
    --dataset="summaries/experiment/data/data_optimized_all_layers_dropout_experiment_<clas>_<batch>.npy"
```
But, there's an error to do this, as shown in following picture:
![image](https://user-images.githubusercontent.com/17549263/35812581-600b4548-0acc-11e8-9ffb-7d0a3b628e51.png)

After reading the code you've upload in "**replayed_distillation/viz**" folder,
I found there's no _dataset_ as input argumentation in print_stats.py.
Should we use `pixel_intensities.py` or `pixel_intensities_batch.py` instead of `print_stats.py`?

If we do have to use these two files, how to use these two files?
And what's the difference to use these two files?

**Comment by irapha** [comment]
Hey Alice, 

The change to "saving batches separately" came after we had made the "pixel intensities over all images" visualization. So we no longer have a script that will go through all batches and compute that visualization. 

I've updated the readme with the proper command to visualize a single batch. If you end up creating another similar script that visualizes over all batches, please feel free to make a PR :)

**Comment by BomboButt** [comment]
Hi @iRapha ,
Thanks for your reply!
